columnSuffix: null
contentColumnType: string
fieldGroup: 8f2a8a85-dbf7-4bb1-8090-3de22a20ace4 # Globals
handle: footerSocialIcons
instructions: null
name: 'Footer Social Icons'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:b22bf838-bae2-4ce7-a9c7-c9be49ce3cb9' # Logos
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 2
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:b22bf838-bae2-4ce7-a9c7-c9be49ce3cb9' # Logos
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:b22bf838-bae2-4ce7-a9c7-c9be49ce3cb9' # Logos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
