fieldLayouts:
  606b7b64-6034-4a4c-9721-9c56bfd90076:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 66065ac2-e18d-4f53-a773-fb0e28d64b21 # Footer Social Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e4804da-c335-4c8b-96c4-8822d77ad929
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8e5edea-cd5d-4bd5-bc7d-2a65922b286e # Footer Social Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3e41dae-7be8-4de1-9105-e4d9cc12e302
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98b2c40f-0607-4a07-aced-fa289111bf4e
        userCondition: null
handle: footer
name: Footer
sortOrder: 5
