defaultPlacement: end
enableVersioning: true
handle: schedule
name: Schedule
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f399f771-94d2-4947-b646-5167ef3e7739: # DIG Conference
    enabledByDefault: true
    hasUrls: true
    template: schedule/_entry
    uriFormat: schedule
type: single
